public class APIDoc extends person implements serilizable, cloneable{
public String eid;
public String ename;
public Float esal;
public String eaddr;
public Employee (String eid, String ename, Float esal, String eaddr){
}
public Employee (String eid, String ename, Float esal){
}
public Employee(String eid, String ename){
}
public Void setEmployeeDetails (String eid, String ename, Float esal, String eaddr){
return sucess;
}
public String search (String eid){
return sucess;
}
public void delete (String eid){
return sucess;
}
}